### ISSUE TITLE
How can I make rpm package using riemann-c-client code?

### ISSUE THREAD

**Issue by lkx007** [algernon/riemann-c-client#16]
How can I make rpm package using riemann-c-client code,  I am in centos6.5.
thanks a lot

**Comment by faxm0dem** [comment]
grab the latest src rpm and adapt it :)

**Comment by algernon** [comment]
I'm afraid I have absolutely no idea. RPM packaging is not my forte. I'd suggest asking on a centos/redhat/etc related forum.
