### ISSUE TITLE
1.10.0 macOS build failure "error: only weak aliases are supported on darwin"

### ISSUE THREAD

**Issue by ilovezfs** [algernon/riemann-c-client#19]
The error is
```
config.status: creating lib/riemann/platform.h
config.status: executing depfiles commands
config.status: executing libtool commands
==> make
  GEN      lib/riemann/proto/riemann.pb-c.c
  CC       lib/riemann/lib_libriemann_client_la-client.lo
lib/riemann/client.c:70:61: error: only weak aliases are supported on darwin
riemann_client_t * riemann_client_new (void) __attribute__((alias("riemann_client_new_default")));
                                                            ^
1 error generated.
make: *** [lib/riemann/lib_libriemann_client_la-client.lo] Error 1
```

If I revert https://github.com/algernon/riemann-c-client/commit/434f820d3c951067cea46a191bbc0dc80ec107b0 (Rearrange symbol versioning and aliases), the build succeeds.

Full build log https://gist.github.com/ilovezfs/4b5310267ca181e6d2ad2cff50921437

**Comment by faxm0dem** [comment]
MacOS instantly seems less magical :-/

**Comment by ilovezfs** [comment]
@faxm0dem :laughing: that's why you need https://www.apple.com/shop/product/MQ052LL/A/magic-keyboard-with-numeric-keypad-us-english

**Comment by algernon** [comment]
Pushed a fix to master, hoping that it will fix the issue. As I don't have access to a MacOS system, and I don't have time to set up Travis to compile there too, @ilovezfs, can you check if it works?

**Comment by ilovezfs** [comment]
@algernon Certainly! We'll see if https://github.com/Homebrew/homebrew-core/pull/14520 is :green_apple:

**Comment by algernon** [comment]
Looks like it passed! Sweet!

I'll tag an 1.10.1 release tonight. Thanks for catching this, and testing the fix!

**Comment by ilovezfs** [comment]
You're welcome. Thanks for the prompt fix!

>I'll tag an 1.10.1 release tonight.

That would be great.
