### ISSUE TITLE
output from riemann-c-client is truncated

### ISSUE THREAD

**Issue by dch** [algernon/riemann-c-client#21]
```
$ riemann-client query -j '(tagged "collectd" and host = "example.org)' | tee /tmp/metrics.json | json_verify
lexical error: invalid char in json text.
                                        [{"time":1506014058,"time_micr
                     (right here) ------^
JSON is invalid
$ ls -AFGl
-rw-r--r--  1 dch      wheel  81920 Sep 21 17:14 metrics.json
```

The size above is suspicious, but repeated running of similar datasets produces various sizes.

The same output from non-JSON data (no -j flag) appears to be complete.

I'm pulling a relatively large dataset out of riemann and the output is always invalid JSON. I can't tell whether the truncation is happening in riemann-client during transit, or just later via json conversion.

1.10.1 FreeBSD 10.1R amd64

**Comment by algernon** [comment]
How big of a dataset are we talking about? Just so I can try reproducing with something similar.

**Comment by dch** [comment]
@algernon I don't have access to this system anymore but I'll re-open this if I can re-trigger the issue. I think the rough size is somewhere between 3k -> 10k events.
