### ISSUE TITLE
Issues while installing riemann c client

### ISSUE THREAD

**Issue by bbsachinbb** [algernon/riemann-c-client#23]
while running command ./configure && make && make check && make install i am getting error that protoc-c is not install but i have 3.2 version of it.

**Comment by faxm0dem** [comment]
did you install the corresponding `-dev` or `devel` package?

**Comment by algernon** [comment]
I think you're mistaking `protoc-compiler` with `protoc-c-compiler`. The former doesn't have a 3.2 version (it's at 1.3.1). You'll need [protobuf-c](https://github.com/protobuf-c/protobuf-c).

**Comment by bbsachinbb** [comment]
i have both protobuf - c and protobuf and version is 1.3.1 but i am still facing same issue .
Is there problem of path setting. Can anyone tell me exact path of protobuf-c
