### ISSUE TITLE
Enhancement: lower GnuTLS requirements

### ISSUE THREAD

**Issue by faxm0dem** [algernon/riemann-c-client#7]
The requirements on the GnuTLS version are pretty high for enterprise GNU/Linux distributions.
Here are the versions shipped in our current environment:

* EL6: 2.8.5-14.el6_5
* EL7: 3.1.18-10.el7_0

**Comment by algernon** [comment]
Not sure I can support 2.8, but 3.1 sounds doable. I'll see what I can do.

**Comment by algernon** [comment]
I had a try with 2.11 (the other version of GnuTLS available in Debian Jessie), the results were disappointing. There are a number of things introduced in 3.3, that riemann-c-client uses, and which would be a huge pain (and burden) to reimplement in a different way for pre-3.3 GnuTLS releases.

* `gnutls_global_init()` is no biggie, I could add a constructor to riemann-c-client.
* `gnutls_certificate_verify_peers()` is one of the big ones in 3.3. The entire certificate validation code relies on the new, more extensible API. Rewriting that part would be a lot of pain, as far as I see.
* `gnutls_handshake_set_timeout()` is 3.1+, and this feature is something I want for the test suite at least, so 2.8.5 is out, doubly so now.

**Comment by algernon** [comment]
I'll keep this open, maybe I'll revisit it again when I have more time to figure out a way to support older GnuTLS releases with less sacrifices than I currently see.

**Comment by faxm0dem** [comment]
I understand, and as far as I'm concerned this can be closed

**Comment by faxm0dem** [comment]
it seems 2.8 is still too low: `gnutls_certificate_set_verify_function` was only introduced in 2.9.10 and doesn't seem to have been backported to 2.8.5 which is the version in EL6. For EL7 this should be fine as it ships 3.1.18.

As far as I'm concerned:

* if the fix is easy, then why not
* if it ain't, well then raise the req to 2.9.10

**Comment by algernon** [comment]
It was fairly easy to work it around, 1.6.1 is out now with the fix. Thanks for noticing!
